Update README and CONTRIBUTING docs
spdx/fsf-api pull request #7
Opened 2021-09-07 22:55 UTC by goneall

Update the documentation with the following changes:
- Change links from the wking repository to the spdx repository
- Update the (previously) broken link to the SPDX mailing list per https://github.com/wking/fsf-api/pull/23
- Add issues and pull request details to CONTRIBUTING
- Add sign-off requirement and DCO reference to CONTRIBUTING
- Change the documentation for how to generate the gh-pages (note: the Makefile was removed in commit https://github.com/spdx/fsf-api/commit/d455634441a9ce3db9c589f70e9a88938d018a02)

2021-09-07 23:02 UTC, goneall commented
@CAM-Gerlach - If you could do a quick review - thanks.

2021-09-08 01:19 UTC, CAM-Gerlach commented
@goneall Thanks! I'll look it over now.

2021-09-08 01:27 UTC, CAM-Gerlach commented
Also, asking here since I'm not sure of another place to ask, but would you be okay with me adding some basic branch protection rules, to avoid the main branch getting clobbered unnecessarily? And with pinging Github support to set this repo as the new upstream in its fork network, for the reasons mentioned on spdx/LicenseListPublisher#77 ?

2021-09-08 02:53 UTC, goneall commented
>  would you be okay with me adding some basic branch protection rules, to avoid the main branch getting clobbered accidentally? And with pinging Github support to set this repo as the new upstream in its fork network, for the reasons mentioned on spdx/LicenseListPublisher#77 ?

No problem - I haven't got around to looking into the "unforking" yet, so if you want to take the lead on that, that would be great

2021-09-08 03:13 UTC, CAM-Gerlach requested changes
Looks good overall and I checked the repo over as a second pair of eyes to make sure there wasn't anything major that was missed. Most of my comments and suggestions related to various textual and formatting issues. I'll submit a PR ASAP to add CI support for build and deploy, for at least a baseline test of PRs and to automatically deploy updated content while obviating the manual, convoluted process described in the contributing guide.

2021-09-08 03:13 UTC, CAM-Gerlach commented on CONTRIBUTING.md
> +---------
```suggestion
## Signing Your Changes

```

Use proper Markdown headings and action-oriented phrasing

2021-09-08 03:13 UTC, CAM-Gerlach commented on CONTRIBUTING.md
> +However you choose to contribute, please sign-off in each of your commits that you license your contributions under the terms of [the Developer Certificate of Origin](https://developercertificate.org
```suggestion
However you choose to contribute, please sign-off each of your commits to certify them under the terms of the [Developer Certificate of Origin](https://developercertificate.org/).
Git has built-in support for signing off: `git commit -s` signs a current commit, and `git rebase --signoff <revision-range>` retroactively signs a range of past commits.
```

Fix grammar and clarify/improve language; and implement one sentence per line.

2021-09-08 03:13 UTC, CAM-Gerlach commented on CONTRIBUTING.md
> +However you choose to contribute, please sign-off in each of your commits that you license your contributions under the terms of [the Developer Certificate of Origin](https://developercertificate.org
Is it a problem that I didn't do this for my already committed changes? I wasn't previously aware this was project policy.

2021-09-08 03:13 UTC, CAM-Gerlach commented on CONTRIBUTING.md
>  The content of the `master` branch is available under [the MIT license](LICENSE.md).
```suggestion
The content of the `master` branch is available under [the MIT (Expat) license](LICENSE.md).
```

Probably worth clarifying here, for the reasons mentioned on the FSF page and elsewhere.

2021-09-08 05:09 UTC, CAM-Gerlach commented
> No problem - I haven't got around to looking into the "unforking" yet, so if you want to take the lead on that, that would be great

Actually, I realized I can't do either that or the branch protect setup without having a high enough permissions on the repo that I can see the settings, so you'll have to take the lead on that I guess

On the good news front, #9 is ready to go pending your review, which (assuming it merges and the deploy works; did you enable Github pages in the settings at the expected URL? I can't see without settings-level access) will allow us to remove the whole section about that from the Contributing Guide entirely.

2021-09-08 17:43 UTC, goneall commented
@CAM-Gerlach - Thanks for the review and feedback.  I updated the files and all suggestions should be taken care of.

BTW - I messed up one of the commit messages referring to the README rather than CONTRIBUTING file.  Since I already pushed the changes and I plan to squash the commits when merging, I don't plan on going through the effort to correct it.

2021-09-08 18:20 UTC, CAM-Gerlach approved these changes
LGTM, thanks @goneall !

2021-09-09 01:06 UTC, merged